# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/tama-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter akari akatsuki aurora apollo,$(TARGET_DEVICE)),)

endif
